#!/bin/sh

if [ -z "$1" ] | [ -z "$2" ]; then
  echo "Usage: build-flatc {platform} {architecture}"
  exit 1
fi

OS="$1"
ARCH="$2"

echo "Will build flatc for platform = $OS, architecture = $ARCH"

ROOTDIR=$(cd .; pwd -P)

echo "Root dir = $ROOTDIR"

mkdir -p $ROOTDIR/out/$OS/$ARCH
docker run -it -v $ROOTDIR/out/$OS/$ARCH:/out \
               -v $ROOTDIR/native-build:/native-build \
               -e FLATBUFFERS_REPO=https://github.com/google/flatbuffers.git \
               -e FLATBUFFERS_COMMIT=v1.12.0 \
               --entrypoint /bin/sh \
       fbbuild-$OS-$ARCH /native-build
